### ISSUE TITLE
Want OTF back

### ISSUE THREAD

**Issue by Mercury13** [notofonts/anatolian-hieroglyphs#1]
### Title 
In Egyptian and Anatolian hieroglyphs OTF has some nice mild hinting  — maybe because of cubic curves? (The rest of your fonts have quadratic curves.)

### Font 
NotoSansAnatolianHieroglyphs-Regular.ttf

### Where the font came from, and when
Site: this repo
Date: 2022-10-05

### Font Version
2.001

### OS name and version
Win10 21H1

### Application name and version
Qt 6.1.3 apps

### Issue
  1. Write anything in small pitch.
  2. Seemingly no hinting
  3. OTF had nice hinting

### Character data
All characters

### Screenshot
**TTF**
![image](https://user-images.githubusercontent.com/10164882/193993371-068bf0d7-a37f-4712-9cbc-bae9cf05eb55.png)

**OTF**
![image](https://user-images.githubusercontent.com/10164882/193993566-f822a5b6-a12c-472b-ba8e-416a11bd9501.png)

**Comment by Mercury13** [comment]
Sorry, have some OTF in GFonts version. Works.

**Comment by Mercury13** [comment]
Well, it’s present, but does not come to release hub. Strange.

**Comment by simoncozens** [comment]
https://github.com/notofonts/anatolian-hieroglyphs/releases/download/NotoSansAnatolianHieroglyphs-v2.001/NotoSansAnatolianHieroglyphs-v2.001.zip has an OTF file, but you're right, it didn't get added to the notofonts.github.io repo. I'll take it out of the metadata and see if it gets picked up again next time around. (Tomorrow)

**Comment by simoncozens** [comment]
OTFs are now back in the Dashboard; when extracting the fonts from the release files, I was using a function which only returned TTFs!
